import tran
from tran import tran_french,tran_french_names,append_gender

#Without names

# tran_french("../../data/data-generated/nonames/bf1.csv","bf1")
# tran_french("../../data/data-generated/nonames/bf2.csv","bf2")
# tran_french("../../data/data-generated/nonames/bf3.csv","bf3")
# tran_french("../../data/data-generated/nonames/bf4.csv","bf4")
# tran_french("../../data/data-generated/nonames/bf5.csv","bf5")
# tran_french("../../data/data-generated/nonames/bm1.csv","bm1")
# tran_french("../../data/data-generated/nonames/bm2.csv","bm2")
# tran_french("../../data/data-generated/nonames/bm3.csv","bm3")
# tran_french("../../data/data-generated/nonames/bm4.csv","bm4")
# tran_french("../../data/data-generated/nonames/bm5.csv","bm5")
# tran_french("../../data/data-generated/nonames/u1.csv","u1")
# tran_french("../../data/data-generated/nonames/u2.csv","u2")
# tran_french("../../data/data-generated/nonames/u3.csv","u3")
# tran_french("../../data/data-generated/nonames/u4.csv","u4")
# tran_french("../../data/data-generated/nonames/u5.csv","u5")

#With names.

tran_french_names("../../data/data-generated/withnames/bf1.csv","bf1")
tran_french_names("../../data/data-generated/withnames/bf2.csv","bf2")
tran_french_names("../../data/data-generated/withnames/bf3.csv","bf3")
tran_french_names("../../data/data-generated/withnames/bf4.csv","bf4")
tran_french_names("../../data/data-generated/withnames/bf5.csv","bf5")
tran_french_names("../../data/data-generated/withnames/bm1.csv","bm1")
tran_french_names("../../data/data-generated/withnames/bm2.csv","bm2")
tran_french_names("../../data/data-generated/withnames/bm3.csv","bm3")
tran_french_names("../../data/data-generated/withnames/bm4.csv","bm4")
tran_french_names("../../data/data-generated/withnames/bm5.csv","bm5")
tran_french_names("../../data/data-generated/withnames/u1.csv","u1")
tran_french_names("../../data/data-generated/withnames/u2.csv","u2")
tran_french_names("../../data/data-generated/withnames/u3.csv","u3")
tran_french_names("../../data/data-generated/withnames/u4.csv","u4")
tran_french_names("../../data/data-generated/withnames/u5.csv","u5")


# append_gender("../../data/data-generated/nonames/bf1.csv","bf1")
# append_gender("../../data/data-generated/nonames/bf2.csv","bf2")
# append_gender("../../data/data-generated/nonames/bf3.csv","bf3")
# append_gender("../../data/data-generated/nonames/bf4.csv","bf4")
# append_gender("../../data/data-generated/nonames/bf5.csv","bf5")
# append_gender("../../data/data-generated/nonames/bm1.csv","bm1")
# append_gender("../../data/data-generated/nonames/bm2.csv","bm2")
# append_gender("../../data/data-generated/nonames/bm3.csv","bm3")
# append_gender("../../data/data-generated/nonames/bm4.csv","bm4")
# append_gender("../../data/data-generated/nonames/bm5.csv","bm5")
# append_gender("../../data/data-generated/nonames/u1.csv","u1")
# append_gender("../../data/data-generated/nonames/u2.csv","u2")
# append_gender("../../data/data-generated/nonames/u3.csv","u3")
# append_gender("../../data/data-generated/nonames/u4.csv","u4")
# append_gender("../../data/data-generated/nonames/u5.csv","u5")
